src/main/java/com/example/demo/controller/LoginController.java, src/main/resources/templates/layoutFile.html
login, logout 구현
thymleaf 조건문으로 로그인 되면 -> 로그아웃 순으로  버튼 변경
=> login, logout 구현

src/main/java/com/example/demo/controller/Product/ProductController.java, src/main/resources/templates/addProductForm.html
588줄에서 선택된 값을 value 변수로 가지고 오고 
input 태그의 id를 가져와서 value를 채워넣으면 model에 들어감
=> product 카테고리 select 부분 버그 해결/ 1개만 model에 넘어가게끔

crawling/crawling_category.py
=> 번개장터 crawling

crawling/crawling_category.py, src/main/java/SilkLoad/config/WebConfig.java, src/main/java/SilkLoad/controller/Cart/CartController.java, src/main/java/SilkLoad/controller/Home/HomeController.java, src/main/java/SilkLoad/controller/Member/MyPageController.java, src/main/java/SilkLoad/controller/Shop/ShopController.java, src/main/java/SilkLoad/dto/CartDto.java, src/main/java/SilkLoad/dto/CrawlingDto.java, src/main/java/SilkLoad/entity/Cart.java, src/main/java/SilkLoad/entity/Crawling.java, src/main/java/SilkLoad/repository/CartRepository.java, src/main/java/SilkLoad/repository/CrawlingRepository.java, src/main/java/SilkLoad/repository/OrderRepository.java, src/main/java/SilkLoad/repository/ProductRepository.java, src/main/java/SilkLoad/service/CartService.java, src/main/java/SilkLoad/service/CrawlingService.java, src/main/java/SilkLoad/service/LoginService.java, src/main/java/SilkLoad/service/MemberService.java, src/main/java/SilkLoad/service/ProductService.java, src/main/resources/application.properties, src/main/resources/templates/detailProduct.html, src/main/resources/templates/index.html, src/main/resources/templates/layoutFile.html, src/main/resources/templates/myPage/memberWishlist.html, src/main/resources/templates/myPage/myPageSidebar.html, src/main/resources/templates/shop.html, src/test/java/SilkLoad/repository/CartRepositoryTest.java, src/test/java/SilkLoad/repository/CrawlingRepositoryTest.java, src/test/java/SilkLoad/repository/ProductRepositoryTest.java
- /shop controller에 페이징된 물품들을 model로 보냄
- 크롤링 테이블 만들기
- CrawlingDto 만들기
- CrawlingService 안에 여성의류, 남성의류, 신발  3개의 카테고리만 보여주기
- (5/22) Cart entity 생성해봄
- (5/24) Cart 테이블에 member(구매자) product 넣기
- [Paging 과정](https://wonin.tistory.com/485)
- 테스트코드는 신경 안써도 될듯 
- th:with 쓰는법
- th에서 spring에서 쓰는 클래스 가져오는법 -> T()
- th에서 number 쓰는법 -> ${#numbers.xxx}
- 테스트 코들에 크롤링데이터 가져오기 있음
- category row만 빼내서 catetgory 별로 view에 뿌릴 수 있다.
(5/22) 
- Cart는 구매자 id와 물품 id만 받으면 된다고 생각함
- 그래서 Cart는 memberid(구매자)와 productid를 @OnetoOne 단방향 매핑함
- product에 있는 memberid는(판매자)라고 생각
- Cart페이지를 보여줄 때 물품id만 가져와서 ProductRepository에 요청하면 될거같다고 생각
(5/24)
- Cart안에 member별로 product를 가져온다.
- ex) memberid = 1이면 1의 product만 가져온다.
=> /shop에 Pagenation 구현

src/main/java/SilkLoad/config/WebConfig.java, src/main/java/SilkLoad/controller/Cart/CartController.java, src/main/java/SilkLoad/controller/Member/MyPageController.java, src/main/java/SilkLoad/dto/CartDto.java, src/main/java/SilkLoad/repository/CartRepository.java, src/main/java/SilkLoad/service/CartService.java, src/main/resources/application.properties, src/main/resources/templates/myPage/memberWishlist.html, src/test/java/SilkLoad/example/service/ProductServiceTest.java, src/test/java/SilkLoad/repository/CartRepositoryTest.java
- cart에 있는 product를 화면에 띄우기
- html에서 form 태그는 put, delete 메소드 지원하지 않음
- cart 테이블에 있는 product를 기준으로 delete 실행
- https://donggu1105.tistory.com/61
=> Cart에 넣기, wishlist에 이미지랑 같이 물품 보기 삭제기능 구현

src/main/java/SilkLoad/controller/Shop/ShopController.java, src/main/java/SilkLoad/service/ProductService.java, src/main/resources/templates/detailProduct.html, src/main/resources/templates/layoutFile.html, src/main/resources/templates/myPage/memberChatRoomList.html, src/main/resources/templates/shop.html, src/test/java/SilkLoad/repository/ProductRepositoryTest.java
- 
- layout의 search바에서 적은 를 기준으로 shop페이지에서 product를 가져올 수 있다.
- 쿼리스트링에 keyword 기준으로 물품 가져오기
- 
=> search 기능 구현

src/main/java/SilkLoad/DemoApplication.java, src/main/java/SilkLoad/controller/Member/MyPageController.java, src/main/java/SilkLoad/controller/Product/OrderController.java, src/main/java/SilkLoad/entity/ChatRoom.java, src/main/java/SilkLoad/entity/ChatRoomEnum/ChatRoomType.java, src/main/java/SilkLoad/repository/ChatRoomRepository.java, src/main/java/SilkLoad/repository/ProductRepository.java, src/main/java/SilkLoad/service/ChatService.java, src/main/java/SilkLoad/service/OrderService.java, src/main/java/SilkLoad/service/ProductService.java, src/main/resources/static/js/jquery-3.6.0.min.js, src/main/resources/templates/myPage/memberChatRoom.html
1시간마다 모든 물품 마감시간 검사하여, 마감시간이 지났을 시 물품 타입 취소로 변경
채팅방 나가기  버튼 추가 및 허가되지 않은 사용자 거부 추가
product reposiroy 의 물품 조회 쿼리문에 productType = sale 조건 추가
=> 채팅방나가기 버튼 수정, 모든 물품 마감시간 조정

src/main/java/SilkLoad/controller/Home/HomeController.java, src/main/java/SilkLoad/controller/Shop/ShopController.java, src/main/java/SilkLoad/service/CartService.java, src/main/java/SilkLoad/service/PagedProductService.java, src/main/java/SilkLoad/service/ProductSearchService.java, src/main/java/SilkLoad/service/ProductService.java, src/test/java/SilkLoad/example/service/ProductServiceTest.java, src/test/java/SilkLoad/repository/ProductRepositoryTest.java
- 
- ProductService안에 있는 paging을 해주는 paged_product를  PagedProductService로 옮김
- ProductService안에 있는 search를해주는 SearchToProductname를  ProductSearchService로 옮김
- ProductServcie 안에 있는 Product를 ProductRecordDto로 변환해주는 getProductRecordDto -> ProductToProductRecordDto로 직관성있게 이름 바꿈
- ProductServcie 안에 있는 List<ProductImage>를 List<ProductImageRecordDto>로 변환해주는 getProductRecordImageListDto -> ImageListToDto로 직관성있게 이름 바꿈
- ProductServcie 안에 있는 List<Product>를 List<ProductRecordDto>로 변환해주는 getProductRecordDtoList-> ListProductToDtoList로 직관성있게 이름 바꿈
- ProductServcie 안에 있는 Category 를 CategoryRecordDto로 변환해주는 getCategoryRecordDto-> CategoryToDto로 직관성있게 이름 바꿈
- ProductServcie 안에 있는 ProductCategoryDto(카테고리 db에서 가져오는 객체) 를 CategoryRecordDto로 변환해주는 getCategoryRecordDto-> CategoryToDto로 직관성있게 이름 바꿈
- …
=> productService 리팩토링(?)

src/main/java/SilkLoad/controller/Shop/ShopController.java, src/main/java/SilkLoad/repository/CrawlingRepository.java, src/main/java/SilkLoad/repository/ProductRepository.java, src/main/java/SilkLoad/service/ChangeProductRecordDto.java, src/main/java/SilkLoad/service/CrawlingService.java, src/main/java/SilkLoad/service/PagedProductService.java, src/main/java/SilkLoad/service/ProductImageService.java, src/main/java/SilkLoad/service/ProductSearchService.java, src/main/java/SilkLoad/service/ProductService.java, src/main/resources/static/css/theme.css, src/main/resources/templates/layoutFile.html
- 
- 기존에 ProductService안에 있는 ProductRecordDto로 만드는 로직은 **ChangeProductRecordDto** 라는 클래스로 만듬 
- ShopController 안에 1차, 2차 카테고리로 구분해서 크롤링 데이터 가져오던거 1,2차 같이 쿼리문 날리도록 변경
- ProductRecordDto는 @Component로 Bean으로 관리되고 있다. 다른 Serivce 객체에도 주입받아서 사용할 수 있다.
- 
=> @Serivce 안에 @Service 구조 바꾸기/ shop 페이지 구조 변경

src/main/java/SilkLoad/controller/Member/MemberController.java, src/main/java/SilkLoad/controller/Product/ProductController.java, src/main/resources/templates/addProductForm.html
<<회원가입>>
- DB에 이미 등록된 id 입력 시, MemberController에서 예외 처리
<<물품등록>>
- 이름, 경매가격, 즉시구매가격에 required 속성 사용 
- addProductForm에 checkNumber 함수 추가 -> 가격 입력 시, 가장 왼쪽에 오는 0을 제거하고 숫자만 입력할 수 있도록 함
- 카테고리 미체크 시, ProductController에서 처리
=> 회원가입, 물품등록 유효성 검사

src/main/java/SilkLoad/controller/Shop/ShopController.java, src/main/java/SilkLoad/repository/CategoryRepository.java, src/main/java/SilkLoad/service/NaverProductService.java, src/main/java/SilkLoad/service/ProductService.java, src/main/resources/application.properties, src/main/resources/templates/detailProduct.html, src/main/resources/templates/index.html, src/main/resources/templates/layoutFile.html, src/main/resources/templates/myPage/memberWishlist.html, src/main/resources/templates/myPage/myPageSidebar.html, src/test/java/SilkLoad/repository/CrawlingRepositoryTest.java
- 
- footer에 다른 사이트, 팀원 소개 넣음
- 쓰지 않는 코드들 정리 
ex)test 안에 있는 코드들
- 
=> 화면의 footer 변경

crawling/crawling_bunjang.py, src/main/resources/application.properties, src/main/resources/templates/myPage/memberChatRoom.html, src/test/java/SilkLoad/entity/productTimeTest.java, src/test/java/SilkLoad/example/service/MemberServiceTest.java, src/test/java/SilkLoad/example/service/ProductServiceTest.java
- 
- crawling_bunjang 쓰레드 활성화
- AWS ec2는 key가 필요함
- key는 나한태만 있어서 접근이 불가능
- rds는 알려준 id, pw로 접속이 가능할듯?
- 
=> aws랑 연동 상태

src/main/resources/templates/addProductForm.html, src/main/resources/templates/detailProduct.html, src/main/resources/templates/login.html
- 물품 등록 페이지와 물품 상세 페이지에서 가격 입력할 때 드래그해서 지울 수 있도록 수정함
- 로그인 페이지에서 로그인 입력창에 자동 포커스 되도록 수정함
=> 가격 드래그해서 삭제, 로그인 자동포커스

crawling/crawling_bunjang.py, src/main/java/SilkLoad/controller/Home/HomeController.java, src/main/java/SilkLoad/service/OrderService.java, src/main/resources/application.properties, src/main/resources/templates/addProductForm.html, src/main/resources/templates/index.html
홈 페이지에 네이버 쇼핑몰 추가 및 경매가 등록 오류 수정
=> 홈 페이지 수정 및 버그 수정

src/main/java/SilkLoad/config/auth/SecurityConfig.java, src/main/java/SilkLoad/controller/Home/HomeController.java, src/main/resources/templates/detailProduct.html, src/main/resources/templates/myPage/memberProfile.html
- 
- ![image](https://user-images.githubusercontent.com/65094518/189556693-e4981259-5663-4955-9135-2f893bdf954c.png)
- 한줄로 나오게 하고 싶었는데 bootstrap을 잘모르겠어서 이정도 까지만
- 
=> detailProduct 페이지 상품 추천 가로로 배치

src/main/java/SilkLoad/config/WebConfig.java, src/main/java/SilkLoad/config/auth/CustomOAuth2UserService.java, src/main/java/SilkLoad/config/auth/SecurityConfig.java, src/main/java/SilkLoad/config/auth/dto/OAuthAttributes.java, src/main/java/SilkLoad/controller/Login/LoginController.java, src/main/java/SilkLoad/dto/MemberFormDto.java, src/main/java/SilkLoad/entity/Members.java, src/main/java/SilkLoad/service/MemberService.java, src/main/resources/templates/layoutFile.html, src/main/resources/templates/login.html
=> 기존 로그인 방식과 OAuth2 방식 혼합

src/main/java/SilkLoad/config/auth/SecurityConfig.java, src/main/java/SilkLoad/controller/Home/HomeController.java, src/main/java/SilkLoad/controller/Login/LoginController.java, src/main/resources/application.properties, src/main/resources/templates/index.html, src/main/resources/templates/layoutFile.html
index 페이지 네이버 쇼핑몰 수정
=> 쇼핑몰 카테고리 3가지로 축소
=> 네이버 쇼핑몰 수정

src/main/resources/application.properties, src/main/resources/templates/addMemberForm.html, src/main/resources/templates/login.html
=> 로그인폼, 회원가입폼 UI 수정

src/main/resources/templates/addMemberForm.html, src/main/resources/templates/login.html
=> 로그인폼, 회원가입폼 너비 수정

crawling/crawling_bunjang.py, src/main/java/SilkLoad/service/NaverProductService.java, src/main/resources/templates/layoutFile.html, src/main/resources/templates/login.html
##번개장터 크롤링 테그  수정
- 이름, 가격, 링크, 카테고리 수정
- 서버 시작시 새로운 물품 가져오도록 변경
=> fix: 크롤링 테그 변경, 네이버 api 자동 동기화 주석해제
